services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_PATH: target/spring-petclinic-2.7.0.jar  # 반드시 정확히 명시
    ports:
      - "80:8080"
    container_name: spring-petclinic
